import Head from "next/head";

export default function ApplicationHead() {
    return (
        <Head>
            <title>RainbowKit App</title>
            <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
            />
            <link href="/favicon.ico" rel="icon" />
        </Head>
    );
}